name: Deploy
on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: lint
      run: npm run lint

    - name: Unit tests
      run: npm run test

  build: 
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run watch 

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: vps-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/vps

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps: 
    - name: Dowload artifact
      uses: actions/download-artifact@v2
      with: 
        name: vps-${{ github.run_id }}-${{ github.run_number }} 
        path: './vps'

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.AZURE_HOST }}
        USERNAME: ${{ secrets.AZURE_USERNAME }}
        PORT: ${{ secrets.AZURE_PORT }}
        KEY: ${{ secrets.SECRET_KEY_SSH }}
      with:
        source: "./vps/"
        target: "/var/www/"
